### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jtdroste** [ubnetdef/scoreengine#1]
- [x] Checks
  - [x] FTP
  - [x] ICMP
  - [x] IMAP
- [ ] Feature Improvements
  - [x] Read from configuration file, not hardcoded into scoring.py
  - [x] Test individual team / check
  - [x] `master.log` write to file
  - [x] Randomization of service_data
    - i.e.: Multiple users
  - [x] IP Address dynamic changing

**Comment by jtdroste** [comment]
Done.
